### ISSUE TITLE
uidemo accessed with tor sometimes soft-blocked by cloudflare

### ISSUE THREAD

**Issue by mlinksva** [commonsearch/cosr-ops#14]
I know long term there will be a commonsearch hidden service #8 but current behavior not a great user experience for most privacy protecting people exploring commonsearch, noted at https://identi.ca/trc/note/t58U-vmiR0GXxZiLpqrJ9g

Background: https://support.cloudflare.com/hc/en-us/articles/203306930-Does-CloudFlare-block-Tor-

May not be worth fixing for demo, or maybe a [participation issue](https://github.com/commonsearch/cosr-participation/issues)?

**Comment by sylvinus** [comment]
Thanks!

I think the hidden service shouldn't be long term. I've been hashing for a while to find a good onion URL, maybe we can just generate a temporary one for the uidemo that people can test & use much sooner.

**Comment by sylvinus** [comment]
I just found how to explicitly whitelist Tor in CloudFlare. I've tried with a bunch of circuits and none of them was blocked. Feel free to reopen if this happens again!
