### ISSUE TITLE
Clarify Python version in the docs

### ISSUE THREAD

**Issue by IvRRimum** [commonsearch/cosr-ops#15]
Hello,

Why there is no documentation of python version ?

Witch python version to use ?

**Comment by IvRRimum** [comment]
Backend uses 2.7( got that from BUILD log ).

**Comment by sylvinus** [comment]
Hi @IvRRimum! Currently Common Search only runs on Python 2.7. It would be indeed good to make that clearer in the docs!

**Comment by IvRRimum** [comment]
Thank you for such a fast response! I will close this!

**Comment by sylvinus** [comment]
You're welcome! Let's close it when we'll have fixed the docs or the readme :)

**Comment by IvRRimum** [comment]
Documentation needs update.

In README you specify that you only need Python installed, python-dev is also required to build the virtualenv.

**Comment by sylvinus** [comment]
@IvRRimum, we switched this repo to use Docker like all the others, that should solve any issue in local install. Let us know if it works well for you!

Best,
