### ISSUE TITLE
Getting error, when calling make virtualenv

### ISSUE THREAD

**Issue by IvRRimum** [commonsearch/cosr-ops#16]
![screenshot from 2016-05-22 23 47 57](https://cloud.githubusercontent.com/assets/5957079/15456392/b7592c66-2077-11e6-8831-c7a1441b179d.png)

Have no idea why.

**Comment by sylvinus** [comment]
Hi @IvRRimum! This seems to be a `virtualenv` issue related to your environment, can you have a look at this and see if it fixes it?
http://stackoverflow.com/questions/36394101/pip-install-locale-error-unsupported-locale-setting

**Comment by IvRRimum** [comment]
Alredy tryed that, researching this as we speak.

**Comment by IvRRimum** [comment]
Resolved!

Problem was in my server locales, so i forced them manually in bashrc( not the cleanest way ).

Added this to my ~/.bashrc 

```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```

It went further, to install the packages, but failed with other error. Will research.
