### ISSUE TITLE
Problems creating stacks

### ISSUE THREAD

**Issue by IvRRimum** [commonsearch/cosr-ops#19]
When i run `make aws_elasticsearch_create` i get the following error:
`The following resource(s) failed to create: [ElasticsearchLbLaunchConfiguration, ElasticsearchMasterLaunchConfiguration, ElasticsearchDataLaunchConfiguration]. . Rollback requested by user.`

Been hung up on this for past few hours.

**Comment by sylvinus** [comment]
Duplicate of #20
