### ISSUE TITLE
How to read from our JSON config in the Makefile?

### ISSUE THREAD

**Issue by sylvinus** [commonsearch/cosr-ops#7]
I'm sure there's an easy solution to this but I'm far from a Makefile expert :)

We just want to read config values stored in a JSON file to avoid duplicating them in the Makefile:
https://github.com/commonsearch/cosr-ops/blob/master/Makefile#L6

**Comment by pawpy** [comment]
How about extending the existing config module (config.py) to print out value given the attribute as first argument and then using lines like below in Makefile?

```
COSR_AWS_STACKNAME := $(shell python config.py AWS_STACKNAME)
COSR_AWS_REGION := $(shell python config.py AWS_REGION)

```

Of course, the print (rather write to stdout) should happen only in main.

Using json parser in python will make is less error prone and extensible, instead of handcrafting sed/awk command and operating it as text.

**Comment by sylvinus** [comment]
Very good suggestion @pawpy! Do you want to do the patch?

**Comment by pawpy** [comment]
Thanks, @sylvinus.  Yes, will patch and send in a pull request.

**Comment by pawpy** [comment]
Hello @sylvinus,

Sorry, got delayed to send the pull request.  I've submitted it now.  However,  I get below error with `make test`.

```
(venv) palwandi@palwandi-VirtualBox:~/git/cosr-ops$ make test
make aws_elasticsearch_validate
make[1]: Entering directory `/home/palwandi/git/cosr-ops'
python aws/cloudformation/template-elasticsearch.py > /tmp/cloudformation-elasticsearch-template.json
template=$(cat /tmp/cloudformation-elasticsearch-template.json) ;\
    aws cloudformation validate-template --template-body "$template"
You must specify a region. You can also configure your region by running "aws configure".
make[1]: *** [aws_elasticsearch_validate] Error 255
make[1]: Leaving directory `/home/palwandi/git/cosr-ops'
make: *** [test] Error 2
```

Tried `aws configure` which asked for AWS credentials (access key id, etc), but I've never used AWS.  Could you provide help on this?

The changes themselves are tested as standalone programs, so I think it wouldn't break any tests.

Thanks.

**Comment by sylvinus** [comment]
Hey @pawpy. Great patch, thanks!

Don't worry about the tests, they just validate the syntax of the cloudformation template for now. They definitely need more love, we could for instance add an easy tutorial to generate a complete CommonSearch instance on AWS, and have `make test` perform an automated version of that. Just added an issue for this. 

thanks again!
